name: FitBuddy
services:
  db:
    image: postgres:15
    # the user dont need to access the database, so this should only be expose internally, for other containers
    expose:
      - "5432"
    container_name: fitbuddy_db
    volumes:
      - fitbuddy_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fitbuddy
      POSTGRES_PASSWORD: fitbuddy
      POSTGRES_DB: fitbuddy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fitbuddy"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - fitbuddy
  backend:
    build:
      context: ./backend/
    container_name: fitbuddy_backend
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.local
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fitbuddy
  frontend:
    build:
      context: ./frontend/
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8000
    container_name: fitbuddy_frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - fitbuddy

# Docker volume for DB and Backend service
volumes:
  fitbuddy_db_volume:

# Bridge network for communication between services
networks:
  fitbuddy:
